### PR TITLE
Update default.xml

### PR DESCRIPTION
**Pull request by pbeeler**
This fixes all current syncing errors regardless of what the CM Members are saying...

### CODE REVIEW

**Comment by V6ser** [comment]
I'm still having problems with sync.

**Comment by pbeeler** [comment]
@Rafd08 That's because this patch never got merged in.  Try mine instead, you might have to delete your current repo source first.  repo init -u https://github.com/pbeeler/AOKP_manifest -b patch-1; repo sync -j1;

**Comment by V6ser** [comment]
@pbeeler You can also use -j32 :)

Thanks :)

**Comment by CoolSilver** [comment]
I questioned that before. Pulled this in and synced first time without trouble.

**Pull request closed without merging**
